remote_theme: "mmistakes/so-simple-theme@3.2.0"

skin: "/assets/css/skins/dark.css"
locale: en-US

title: "Liu Yue"
description: "Liu Yue's personal website in English."
url: "https://euyuil.com"
baseurl: ""
logo: "images/liuyue-logo-sosimple-dark.png"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

author:
  name: "Liu Yue"
  email: "euyuil@gmail.com"
  twitter: euyuil
