remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: "Liu Yue"
description: "Liu Yue's personal website."
url: "https://euyuil.com"
baseurl: ""

author:
  name: "Liu Yue"
  email: "euyuil@gmail.com"
  twitter_username: euyuil
  github_username: euyuil
